auth_enabled: false
server:
  http_listen_port: ${LOKI_HTTP_LISTEN_PORT}
  log_level: ${LOKI_LOG_LEVEL}
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: ${LOKI_WAL_DIR}
schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: ${LOKI_INDEX_DIR}
    cache_location: ${LOKI_CACHE_DIR}
    shared_store: filesystem
  filesystem:
    directory: ${LOKI_CHUNKS_DIR}
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  volume_enabled: true
chunk_store_config:
  max_look_back_period: 0s
table_manager:
  retention_deletes_enabled: true
  retention_period: ${LOKI_RETENTION_PERIOD}
compactor:
  working_directory: ${LOKI_COMPACTOR_DIR}
  shared_store: filesystem
