#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/config/.env}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

SERVICE_HOST="${SERVICE_HOST:-100.105.80.22}"
RAG_HOST="${RAG_HOST:-${SERVICE_HOST}:${RAG_SERVICE_PORT:-50054}}"
LLM_HOST="${LLM_HOST:-${SERVICE_HOST}:${LLM_SERVICE_PORT:-50051}}"
MINIO_GRPC_HOST="${MINIO_GRPC_HOST:-${SERVICE_HOST}:${MINIO_SERVICE_PORT:-50052}}"
EMBEDDING_HOST="${EMBEDDING_HOST:-${SERVICE_HOST}:${EMBEDDING_SERVICE_PORT:-50053}}"
PROCESS_FILE_HOST="${PROCESS_FILE_HOST:-${SERVICE_HOST}:${PROCESS_FILE_SERVICE_PORT:-50055}}"
KAFKA_BOOTSTRAP="${KAFKA_BOOTSTRAP:-${KAFKA_BROKERS:-localhost:9092}}"
KAFKA_CONTAINER="${KAFKA_CONTAINER:-kafka}"

MINIO_BUCKET="${MINIO_BUCKET:-${MINIO_DEFAULT_BUCKET:-rag-default}}"
MINIO_SERVER_URL="${MINIO_SERVER_URL:-http://localhost:9000}"

export SCRIPT_DIR ROOT_DIR ENV_FILE SERVICE_HOST
export RAG_HOST LLM_HOST MINIO_GRPC_HOST EMBEDDING_HOST PROCESS_FILE_HOST
export KAFKA_BOOTSTRAP KAFKA_CONTAINER MINIO_BUCKET MINIO_SERVER_URL
