// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/llm_service.proto

package llm_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LlmService_GenerateTextToText_FullMethodName  = "/LlmService/GenerateTextToText"
	LlmService_GenerateTextToImage_FullMethodName = "/LlmService/GenerateTextToImage"
)

// LlmServiceClient is the client API for LlmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmServiceClient interface {
	GenerateTextToText(ctx context.Context, in *TextToTextRequest, opts ...grpc.CallOption) (*LLMResponse, error)
	GenerateTextToImage(ctx context.Context, in *TextToImageRequest, opts ...grpc.CallOption) (*LLMResponse, error)
}

type llmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmServiceClient(cc grpc.ClientConnInterface) LlmServiceClient {
	return &llmServiceClient{cc}
}

func (c *llmServiceClient) GenerateTextToText(ctx context.Context, in *TextToTextRequest, opts ...grpc.CallOption) (*LLMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLMResponse)
	err := c.cc.Invoke(ctx, LlmService_GenerateTextToText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmServiceClient) GenerateTextToImage(ctx context.Context, in *TextToImageRequest, opts ...grpc.CallOption) (*LLMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLMResponse)
	err := c.cc.Invoke(ctx, LlmService_GenerateTextToImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlmServiceServer is the server API for LlmService service.
// All implementations must embed UnimplementedLlmServiceServer
// for forward compatibility.
type LlmServiceServer interface {
	GenerateTextToText(context.Context, *TextToTextRequest) (*LLMResponse, error)
	GenerateTextToImage(context.Context, *TextToImageRequest) (*LLMResponse, error)
	mustEmbedUnimplementedLlmServiceServer()
}

// UnimplementedLlmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmServiceServer struct{}

func (UnimplementedLlmServiceServer) GenerateTextToText(context.Context, *TextToTextRequest) (*LLMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateTextToText not implemented")
}
func (UnimplementedLlmServiceServer) GenerateTextToImage(context.Context, *TextToImageRequest) (*LLMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateTextToImage not implemented")
}
func (UnimplementedLlmServiceServer) mustEmbedUnimplementedLlmServiceServer() {}
func (UnimplementedLlmServiceServer) testEmbeddedByValue()                    {}

// UnsafeLlmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmServiceServer will
// result in compilation errors.
type UnsafeLlmServiceServer interface {
	mustEmbedUnimplementedLlmServiceServer()
}

func RegisterLlmServiceServer(s grpc.ServiceRegistrar, srv LlmServiceServer) {
	// If the following call panics, it indicates UnimplementedLlmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LlmService_ServiceDesc, srv)
}

func _LlmService_GenerateTextToText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextToTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServiceServer).GenerateTextToText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmService_GenerateTextToText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServiceServer).GenerateTextToText(ctx, req.(*TextToTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmService_GenerateTextToImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextToImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServiceServer).GenerateTextToImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmService_GenerateTextToImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServiceServer).GenerateTextToImage(ctx, req.(*TextToImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LlmService_ServiceDesc is the grpc.ServiceDesc for LlmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LlmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LlmService",
	HandlerType: (*LlmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateTextToText",
			Handler:    _LlmService_GenerateTextToText_Handler,
		},
		{
			MethodName: "GenerateTextToImage",
			Handler:    _LlmService_GenerateTextToImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/llm_service.proto",
}
