// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: proto/llm_service.proto

package llm_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LlmService_GenerateContent_FullMethodName       = "/LlmService/GenerateContent"
	LlmService_GenerateContentStream_FullMethodName = "/LlmService/GenerateContentStream"
)

// LlmServiceClient is the client API for LlmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LlmServiceClient interface {
	GenerateContent(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	GenerateContentStream(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
}

type llmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmServiceClient(cc grpc.ClientConnInterface) LlmServiceClient {
	return &llmServiceClient{cc}
}

func (c *llmServiceClient) GenerateContent(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, LlmService_GenerateContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmServiceClient) GenerateContentStream(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LlmService_ServiceDesc.Streams[0], LlmService_GenerateContentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LlmService_GenerateContentStreamClient = grpc.ServerStreamingClient[GenerateResponse]

// LlmServiceServer is the server API for LlmService service.
// All implementations must embed UnimplementedLlmServiceServer
// for forward compatibility.
type LlmServiceServer interface {
	GenerateContent(context.Context, *GenerateRequest) (*GenerateResponse, error)
	GenerateContentStream(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	mustEmbedUnimplementedLlmServiceServer()
}

// UnimplementedLlmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmServiceServer struct{}

func (UnimplementedLlmServiceServer) GenerateContent(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateContent not implemented")
}
func (UnimplementedLlmServiceServer) GenerateContentStream(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateContentStream not implemented")
}
func (UnimplementedLlmServiceServer) mustEmbedUnimplementedLlmServiceServer() {}
func (UnimplementedLlmServiceServer) testEmbeddedByValue()                    {}

// UnsafeLlmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmServiceServer will
// result in compilation errors.
type UnsafeLlmServiceServer interface {
	mustEmbedUnimplementedLlmServiceServer()
}

func RegisterLlmServiceServer(s grpc.ServiceRegistrar, srv LlmServiceServer) {
	// If the following call panics, it indicates UnimplementedLlmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LlmService_ServiceDesc, srv)
}

func _LlmService_GenerateContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmServiceServer).GenerateContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmService_GenerateContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmServiceServer).GenerateContent(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmService_GenerateContentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LlmServiceServer).GenerateContentStream(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LlmService_GenerateContentStreamServer = grpc.ServerStreamingServer[GenerateResponse]

// LlmService_ServiceDesc is the grpc.ServiceDesc for LlmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LlmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LlmService",
	HandlerType: (*LlmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateContent",
			Handler:    _LlmService_GenerateContent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateContentStream",
			Handler:       _LlmService_GenerateContentStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/llm_service.proto",
}
