// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/llm_service.proto

package llm_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextToTextRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Model           string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Temperature     float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Prompt          string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	History         []*ChatHistory         `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	StructureOutput map[string]string      `protobuf:"bytes,5,rep,name=structure_output,json=structureOutput,proto3" json:"structure_output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TextToTextRequest) Reset() {
	*x = TextToTextRequest{}
	mi := &file_proto_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextToTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToTextRequest) ProtoMessage() {}

func (x *TextToTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToTextRequest.ProtoReflect.Descriptor instead.
func (*TextToTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *TextToTextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TextToTextRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TextToTextRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TextToTextRequest) GetHistory() []*ChatHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *TextToTextRequest) GetStructureOutput() map[string]string {
	if x != nil {
		return x.StructureOutput
	}
	return nil
}

type TextToImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Model           string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Temperature     float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	ImagePath       string                 `protobuf:"bytes,3,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	Prompt          string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	History         []*ChatHistory         `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	StructureOutput map[string]string      `protobuf:"bytes,6,rep,name=structure_output,json=structureOutput,proto3" json:"structure_output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TextToImageRequest) Reset() {
	*x = TextToImageRequest{}
	mi := &file_proto_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextToImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToImageRequest) ProtoMessage() {}

func (x *TextToImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToImageRequest.ProtoReflect.Descriptor instead.
func (*TextToImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *TextToImageRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TextToImageRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TextToImageRequest) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *TextToImageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TextToImageRequest) GetHistory() []*ChatHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *TextToImageRequest) GetStructureOutput() map[string]string {
	if x != nil {
		return x.StructureOutput
	}
	return nil
}

type ChatHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistory) Reset() {
	*x = ChatHistory{}
	mi := &file_proto_llm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistory) ProtoMessage() {}

func (x *ChatHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistory.ProtoReflect.Descriptor instead.
func (*ChatHistory) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{2}
}

func (x *ChatHistory) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatHistory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LLMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Json          map[string]string      `protobuf:"bytes,2,rep,name=json,proto3" json:"json,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMResponse) Reset() {
	*x = LLMResponse{}
	mi := &file_proto_llm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMResponse) ProtoMessage() {}

func (x *LLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMResponse.ProtoReflect.Descriptor instead.
func (*LLMResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{3}
}

func (x *LLMResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LLMResponse) GetJson() map[string]string {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_proto_llm_service_proto protoreflect.FileDescriptor

const file_proto_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/llm_service.proto\"\xa3\x02\n" +
	"\x11TextToTextRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12&\n" +
	"\ahistory\x18\x04 \x03(\v2\f.ChatHistoryR\ahistory\x12R\n" +
	"\x10structure_output\x18\x05 \x03(\v2'.TextToTextRequest.StructureOutputEntryR\x0fstructureOutput\x1aB\n" +
	"\x14StructureOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x02\n" +
	"\x12TextToImageRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"image_path\x18\x03 \x01(\tR\timagePath\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12&\n" +
	"\ahistory\x18\x05 \x03(\v2\f.ChatHistoryR\ahistory\x12S\n" +
	"\x10structure_output\x18\x06 \x03(\v2(.TextToImageRequest.StructureOutputEntryR\x0fstructureOutput\x1aB\n" +
	"\x14StructureOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\vChatHistory\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x86\x01\n" +
	"\vLLMResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12*\n" +
	"\x04json\x18\x02 \x03(\v2\x16.LLMResponse.JsonEntryR\x04json\x1a7\n" +
	"\tJsonEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012~\n" +
	"\n" +
	"LlmService\x126\n" +
	"\x12GenerateTextToText\x12\x12.TextToTextRequest\x1a\f.LLMResponse\x128\n" +
	"\x13GenerateTextToImage\x12\x13.TextToImageRequest\x1a\f.LLMResponseB)Z'rag_imtotext_texttoim/proto;llm_serviceb\x06proto3"

var (
	file_proto_llm_service_proto_rawDescOnce sync.Once
	file_proto_llm_service_proto_rawDescData []byte
)

func file_proto_llm_service_proto_rawDescGZIP() []byte {
	file_proto_llm_service_proto_rawDescOnce.Do(func() {
		file_proto_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_llm_service_proto_rawDesc), len(file_proto_llm_service_proto_rawDesc)))
	})
	return file_proto_llm_service_proto_rawDescData
}

var file_proto_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_llm_service_proto_goTypes = []any{
	(*TextToTextRequest)(nil),  // 0: TextToTextRequest
	(*TextToImageRequest)(nil), // 1: TextToImageRequest
	(*ChatHistory)(nil),        // 2: ChatHistory
	(*LLMResponse)(nil),        // 3: LLMResponse
	nil,                        // 4: TextToTextRequest.StructureOutputEntry
	nil,                        // 5: TextToImageRequest.StructureOutputEntry
	nil,                        // 6: LLMResponse.JsonEntry
}
var file_proto_llm_service_proto_depIdxs = []int32{
	2, // 0: TextToTextRequest.history:type_name -> ChatHistory
	4, // 1: TextToTextRequest.structure_output:type_name -> TextToTextRequest.StructureOutputEntry
	2, // 2: TextToImageRequest.history:type_name -> ChatHistory
	5, // 3: TextToImageRequest.structure_output:type_name -> TextToImageRequest.StructureOutputEntry
	6, // 4: LLMResponse.json:type_name -> LLMResponse.JsonEntry
	0, // 5: LlmService.GenerateTextToText:input_type -> TextToTextRequest
	1, // 6: LlmService.GenerateTextToImage:input_type -> TextToImageRequest
	3, // 7: LlmService.GenerateTextToText:output_type -> LLMResponse
	3, // 8: LlmService.GenerateTextToImage:output_type -> LLMResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_llm_service_proto_init() }
func file_proto_llm_service_proto_init() {
	if File_proto_llm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_llm_service_proto_rawDesc), len(file_proto_llm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_llm_service_proto_goTypes,
		DependencyIndexes: file_proto_llm_service_proto_depIdxs,
		MessageInfos:      file_proto_llm_service_proto_msgTypes,
	}.Build()
	File_proto_llm_service_proto = out.File
	file_proto_llm_service_proto_goTypes = nil
	file_proto_llm_service_proto_depIdxs = nil
}
