// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: minio_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinioService_DeleteFile_FullMethodName       = "/MinioService/DeleteFile"
	MinioService_PresignUploadURL_FullMethodName = "/MinioService/PresignUploadURL"
)

// MinioServiceClient is the client API for MinioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinioServiceClient interface {
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	PresignUploadURL(ctx context.Context, in *PresignUploadURLRequest, opts ...grpc.CallOption) (*PresignUploadURLResponse, error)
}

type minioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMinioServiceClient(cc grpc.ClientConnInterface) MinioServiceClient {
	return &minioServiceClient{cc}
}

func (c *minioServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, MinioService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minioServiceClient) PresignUploadURL(ctx context.Context, in *PresignUploadURLRequest, opts ...grpc.CallOption) (*PresignUploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignUploadURLResponse)
	err := c.cc.Invoke(ctx, MinioService_PresignUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinioServiceServer is the server API for MinioService service.
// All implementations must embed UnimplementedMinioServiceServer
// for forward compatibility.
type MinioServiceServer interface {
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	PresignUploadURL(context.Context, *PresignUploadURLRequest) (*PresignUploadURLResponse, error)
	mustEmbedUnimplementedMinioServiceServer()
}

// UnimplementedMinioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinioServiceServer struct{}

func (UnimplementedMinioServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedMinioServiceServer) PresignUploadURL(context.Context, *PresignUploadURLRequest) (*PresignUploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PresignUploadURL not implemented")
}
func (UnimplementedMinioServiceServer) mustEmbedUnimplementedMinioServiceServer() {}
func (UnimplementedMinioServiceServer) testEmbeddedByValue()                      {}

// UnsafeMinioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinioServiceServer will
// result in compilation errors.
type UnsafeMinioServiceServer interface {
	mustEmbedUnimplementedMinioServiceServer()
}

func RegisterMinioServiceServer(s grpc.ServiceRegistrar, srv MinioServiceServer) {
	// If the following call panics, it indicates UnimplementedMinioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinioService_ServiceDesc, srv)
}

func _MinioService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinioServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinioService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinioServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinioService_PresignUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinioServiceServer).PresignUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinioService_PresignUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinioServiceServer).PresignUploadURL(ctx, req.(*PresignUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MinioService_ServiceDesc is the grpc.ServiceDesc for MinioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MinioService",
	HandlerType: (*MinioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteFile",
			Handler:    _MinioService_DeleteFile_Handler,
		},
		{
			MethodName: "PresignUploadURL",
			Handler:    _MinioService_PresignUploadURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minio_service.proto",
}
