// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: minio_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_minio_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minio_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_minio_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteFileRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *DeleteFileRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_minio_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minio_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_minio_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PresignUploadURLRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BucketName       string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	ObjectKey        string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ExpiresInSeconds int64                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PresignUploadURLRequest) Reset() {
	*x = PresignUploadURLRequest{}
	mi := &file_minio_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadURLRequest) ProtoMessage() {}

func (x *PresignUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minio_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadURLRequest.ProtoReflect.Descriptor instead.
func (*PresignUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_minio_service_proto_rawDescGZIP(), []int{2}
}

func (x *PresignUploadURLRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *PresignUploadURLRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignUploadURLRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type PresignUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignUploadURLResponse) Reset() {
	*x = PresignUploadURLResponse{}
	mi := &file_minio_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignUploadURLResponse) ProtoMessage() {}

func (x *PresignUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minio_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignUploadURLResponse.ProtoReflect.Descriptor instead.
func (*PresignUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_minio_service_proto_rawDescGZIP(), []int{3}
}

func (x *PresignUploadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PresignUploadURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_minio_service_proto protoreflect.FileDescriptor

const file_minio_service_proto_rawDesc = "" +
	"\n" +
	"\x13minio_service.proto\"S\n" +
	"\x11DeleteFileRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x01\n" +
	"\x17PresignUploadURLRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\"F\n" +
	"\x18PresignUploadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x8e\x01\n" +
	"\fMinioService\x125\n" +
	"\n" +
	"DeleteFile\x12\x12.DeleteFileRequest\x1a\x13.DeleteFileResponse\x12G\n" +
	"\x10PresignUploadURL\x12\x18.PresignUploadURLRequest\x1a\x19.PresignUploadURLResponseB)Z'rag_imagetotext_texttoimage/proto;protob\x06proto3"

var (
	file_minio_service_proto_rawDescOnce sync.Once
	file_minio_service_proto_rawDescData []byte
)

func file_minio_service_proto_rawDescGZIP() []byte {
	file_minio_service_proto_rawDescOnce.Do(func() {
		file_minio_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_minio_service_proto_rawDesc), len(file_minio_service_proto_rawDesc)))
	})
	return file_minio_service_proto_rawDescData
}

var file_minio_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_minio_service_proto_goTypes = []any{
	(*DeleteFileRequest)(nil),        // 0: DeleteFileRequest
	(*DeleteFileResponse)(nil),       // 1: DeleteFileResponse
	(*PresignUploadURLRequest)(nil),  // 2: PresignUploadURLRequest
	(*PresignUploadURLResponse)(nil), // 3: PresignUploadURLResponse
}
var file_minio_service_proto_depIdxs = []int32{
	0, // 0: MinioService.DeleteFile:input_type -> DeleteFileRequest
	2, // 1: MinioService.PresignUploadURL:input_type -> PresignUploadURLRequest
	1, // 2: MinioService.DeleteFile:output_type -> DeleteFileResponse
	3, // 3: MinioService.PresignUploadURL:output_type -> PresignUploadURLResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_minio_service_proto_init() }
func file_minio_service_proto_init() {
	if File_minio_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minio_service_proto_rawDesc), len(file_minio_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minio_service_proto_goTypes,
		DependencyIndexes: file_minio_service_proto_depIdxs,
		MessageInfos:      file_minio_service_proto_msgTypes,
	}.Build()
	File_minio_service_proto = out.File
	file_minio_service_proto_goTypes = nil
	file_minio_service_proto_depIdxs = nil
}
