// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: model_deep_learning.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedTextRequest) Reset() {
	*x = EmbedTextRequest{}
	mi := &file_model_deep_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedTextRequest) ProtoMessage() {}

func (x *EmbedTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_deep_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedTextRequest.ProtoReflect.Descriptor instead.
func (*EmbedTextRequest) Descriptor() ([]byte, []int) {
	return file_model_deep_learning_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // Assuming 768 dimensions
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`         // Dimension of the embedding (e.g., 768)
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`               // Status of the embedding operation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedTextResponse) Reset() {
	*x = EmbedTextResponse{}
	mi := &file_model_deep_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedTextResponse) ProtoMessage() {}

func (x *EmbedTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_deep_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedTextResponse.ProtoReflect.Descriptor instead.
func (*EmbedTextResponse) Descriptor() ([]byte, []int) {
	return file_model_deep_learning_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedTextResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedTextResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *EmbedTextResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type EmbedImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        [][]byte               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`      // List of image data in bytes
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`       // Image width (e.g., 384)
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`     // Image height (e.g., 384)
	Channels      int32                  `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"` // Number of channels (e.g., 3 for RGB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedImageRequest) Reset() {
	*x = EmbedImageRequest{}
	mi := &file_model_deep_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedImageRequest) ProtoMessage() {}

func (x *EmbedImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_deep_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedImageRequest.ProtoReflect.Descriptor instead.
func (*EmbedImageRequest) Descriptor() ([]byte, []int) {
	return file_model_deep_learning_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedImageRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *EmbedImageRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *EmbedImageRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *EmbedImageRequest) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type EmbedImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // Assuming 768 dimensions
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`         // Dimension of the embedding (e.g., 768)
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`               // Status of the embedding operation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedImageResponse) Reset() {
	*x = EmbedImageResponse{}
	mi := &file_model_deep_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedImageResponse) ProtoMessage() {}

func (x *EmbedImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_deep_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedImageResponse.ProtoReflect.Descriptor instead.
func (*EmbedImageResponse) Descriptor() ([]byte, []int) {
	return file_model_deep_learning_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedImageResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedImageResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *EmbedImageResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_model_deep_learning_proto protoreflect.FileDescriptor

const file_model_deep_learning_proto_rawDesc = "" +
	"\n" +
	"\x19model_deep_learning.proto\"&\n" +
	"\x10EmbedTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"g\n" +
	"\x11EmbedTextResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"u\n" +
	"\x11EmbedImageRequest\x12\x16\n" +
	"\x06images\x18\x01 \x03(\fR\x06images\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\"h\n" +
	"\x12EmbedImageResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status2\x80\x01\n" +
	"\x13DeepLearningService\x122\n" +
	"\tEmbedText\x12\x11.EmbedTextRequest\x1a\x12.EmbedTextResponse\x125\n" +
	"\n" +
	"EmbedImage\x12\x12.EmbedImageRequest\x1a\x13.EmbedImageResponseB)Z'rag_imagetotext_texttoimage/proto;protob\x06proto3"

var (
	file_model_deep_learning_proto_rawDescOnce sync.Once
	file_model_deep_learning_proto_rawDescData []byte
)

func file_model_deep_learning_proto_rawDescGZIP() []byte {
	file_model_deep_learning_proto_rawDescOnce.Do(func() {
		file_model_deep_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_deep_learning_proto_rawDesc), len(file_model_deep_learning_proto_rawDesc)))
	})
	return file_model_deep_learning_proto_rawDescData
}

var file_model_deep_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_deep_learning_proto_goTypes = []any{
	(*EmbedTextRequest)(nil),   // 0: EmbedTextRequest
	(*EmbedTextResponse)(nil),  // 1: EmbedTextResponse
	(*EmbedImageRequest)(nil),  // 2: EmbedImageRequest
	(*EmbedImageResponse)(nil), // 3: EmbedImageResponse
}
var file_model_deep_learning_proto_depIdxs = []int32{
	0, // 0: DeepLearningService.EmbedText:input_type -> EmbedTextRequest
	2, // 1: DeepLearningService.EmbedImage:input_type -> EmbedImageRequest
	1, // 2: DeepLearningService.EmbedText:output_type -> EmbedTextResponse
	3, // 3: DeepLearningService.EmbedImage:output_type -> EmbedImageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_deep_learning_proto_init() }
func file_model_deep_learning_proto_init() {
	if File_model_deep_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_deep_learning_proto_rawDesc), len(file_model_deep_learning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_deep_learning_proto_goTypes,
		DependencyIndexes: file_model_deep_learning_proto_depIdxs,
		MessageInfos:      file_model_deep_learning_proto_msgTypes,
	}.Build()
	File_model_deep_learning_proto = out.File
	file_model_deep_learning_proto_goTypes = nil
	file_model_deep_learning_proto_depIdxs = nil
}
