// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: rag_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_CreateCollection_FullMethodName  = "/RagService/CreateCollection"
	RagService_DeleteCollection_FullMethodName  = "/RagService/DeleteCollection"
	RagService_InsertPoint_FullMethodName       = "/RagService/InsertPoint"
	RagService_SearchPoint_FullMethodName       = "/RagService/SearchPoint"
	RagService_DeletePointFilter_FullMethodName = "/RagService/DeletePointFilter"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagServiceClient interface {
	// Collection management
	CreateCollection(ctx context.Context, in *SchemaCollection, opts ...grpc.CallOption) (*ResponseCreateCollection, error)
	DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*ResponseDeleteCollection, error)
	// Point operations
	InsertPoint(ctx context.Context, in *InsertPointRequest, opts ...grpc.CallOption) (*ResponseInsertPoint, error)
	SearchPoint(ctx context.Context, in *SearchPointRequest, opts ...grpc.CallOption) (*ResponseSearchPoint, error)
	DeletePointFilter(ctx context.Context, in *DeletePointFilterRequest, opts ...grpc.CallOption) (*ResponseDeletePointFilter, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) CreateCollection(ctx context.Context, in *SchemaCollection, opts ...grpc.CallOption) (*ResponseCreateCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseCreateCollection)
	err := c.cc.Invoke(ctx, RagService_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*ResponseDeleteCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseDeleteCollection)
	err := c.cc.Invoke(ctx, RagService_DeleteCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) InsertPoint(ctx context.Context, in *InsertPointRequest, opts ...grpc.CallOption) (*ResponseInsertPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseInsertPoint)
	err := c.cc.Invoke(ctx, RagService_InsertPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) SearchPoint(ctx context.Context, in *SearchPointRequest, opts ...grpc.CallOption) (*ResponseSearchPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseSearchPoint)
	err := c.cc.Invoke(ctx, RagService_SearchPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeletePointFilter(ctx context.Context, in *DeletePointFilterRequest, opts ...grpc.CallOption) (*ResponseDeletePointFilter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseDeletePointFilter)
	err := c.cc.Invoke(ctx, RagService_DeletePointFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
type RagServiceServer interface {
	// Collection management
	CreateCollection(context.Context, *SchemaCollection) (*ResponseCreateCollection, error)
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*ResponseDeleteCollection, error)
	// Point operations
	InsertPoint(context.Context, *InsertPointRequest) (*ResponseInsertPoint, error)
	SearchPoint(context.Context, *SearchPointRequest) (*ResponseSearchPoint, error)
	DeletePointFilter(context.Context, *DeletePointFilterRequest) (*ResponseDeletePointFilter, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) CreateCollection(context.Context, *SchemaCollection) (*ResponseCreateCollection, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedRagServiceServer) DeleteCollection(context.Context, *DeleteCollectionRequest) (*ResponseDeleteCollection, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCollection not implemented")
}
func (UnimplementedRagServiceServer) InsertPoint(context.Context, *InsertPointRequest) (*ResponseInsertPoint, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertPoint not implemented")
}
func (UnimplementedRagServiceServer) SearchPoint(context.Context, *SearchPointRequest) (*ResponseSearchPoint, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPoint not implemented")
}
func (UnimplementedRagServiceServer) DeletePointFilter(context.Context, *DeletePointFilterRequest) (*ResponseDeletePointFilter, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePointFilter not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call panics, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).CreateCollection(ctx, req.(*SchemaCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeleteCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeleteCollection(ctx, req.(*DeleteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_InsertPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).InsertPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_InsertPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).InsertPoint(ctx, req.(*InsertPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_SearchPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).SearchPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_SearchPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).SearchPoint(ctx, req.(*SearchPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeletePointFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePointFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeletePointFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeletePointFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeletePointFilter(ctx, req.(*DeletePointFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _RagService_CreateCollection_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _RagService_DeleteCollection_Handler,
		},
		{
			MethodName: "InsertPoint",
			Handler:    _RagService_InsertPoint_Handler,
		},
		{
			MethodName: "SearchPoint",
			Handler:    _RagService_SearchPoint_Handler,
		},
		{
			MethodName: "DeletePointFilter",
			Handler:    _RagService_DeletePointFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag_service.proto",
}
