// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rag_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CollectionVectorConfig maps to ports.CollectionVectorConfig.
// distance: "cosine" | "dot" | "euclid" | "manhattan"
type CollectionVectorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Distance      string                 `protobuf:"bytes,3,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionVectorConfig) Reset() {
	*x = CollectionVectorConfig{}
	mi := &file_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionVectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionVectorConfig) ProtoMessage() {}

func (x *CollectionVectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionVectorConfig.ProtoReflect.Descriptor instead.
func (*CollectionVectorConfig) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionVectorConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionVectorConfig) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CollectionVectorConfig) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

// SchemaCollection maps to ports.CollectionSchema.
type SchemaCollection struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Name              string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vectors           []*CollectionVectorConfig `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Shards            uint32                    `protobuf:"varint,3,opt,name=shards,proto3" json:"shards,omitempty"`
	ReplicationFactor uint32                    `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	OnDiskPayload     bool                      `protobuf:"varint,5,opt,name=on_disk_payload,json=onDiskPayload,proto3" json:"on_disk_payload,omitempty"`
	OptimizersMemmap  bool                      `protobuf:"varint,6,opt,name=optimizers_memmap,json=optimizersMemmap,proto3" json:"optimizers_memmap,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SchemaCollection) Reset() {
	*x = SchemaCollection{}
	mi := &file_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaCollection) ProtoMessage() {}

func (x *SchemaCollection) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaCollection.ProtoReflect.Descriptor instead.
func (*SchemaCollection) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaCollection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaCollection) GetVectors() []*CollectionVectorConfig {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *SchemaCollection) GetShards() uint32 {
	if x != nil {
		return x.Shards
	}
	return 0
}

func (x *SchemaCollection) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *SchemaCollection) GetOnDiskPayload() bool {
	if x != nil {
		return x.OnDiskPayload
	}
	return false
}

func (x *SchemaCollection) GetOptimizersMemmap() bool {
	if x != nil {
		return x.OptimizersMemmap
	}
	return false
}

type ResponseCreateCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateCollection) Reset() {
	*x = ResponseCreateCollection{}
	mi := &file_rag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateCollection) ProtoMessage() {}

func (x *ResponseCreateCollection) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateCollection.ProtoReflect.Descriptor instead.
func (*ResponseCreateCollection) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseCreateCollection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseCreateCollection) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_rag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseDeleteCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseDeleteCollection) Reset() {
	*x = ResponseDeleteCollection{}
	mi := &file_rag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDeleteCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDeleteCollection) ProtoMessage() {}

func (x *ResponseDeleteCollection) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDeleteCollection.ProtoReflect.Descriptor instead.
func (*ResponseDeleteCollection) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseDeleteCollection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseDeleteCollection) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type VectorObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorObject) Reset() {
	*x = VectorObject{}
	mi := &file_rag_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorObject) ProtoMessage() {}

func (x *VectorObject) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorObject.ProtoReflect.Descriptor instead.
func (*VectorObject) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{5}
}

func (x *VectorObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VectorObject) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorObject  []*VectorObject        `protobuf:"bytes,1,rep,name=vectorObject,proto3" json:"vectorObject,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_rag_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{6}
}

func (x *Point) GetVectorObject() []*VectorObject {
	if x != nil {
		return x.VectorObject
	}
	return nil
}

func (x *Point) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type InsertPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Points         []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InsertPointRequest) Reset() {
	*x = InsertPointRequest{}
	mi := &file_rag_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPointRequest) ProtoMessage() {}

func (x *InsertPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPointRequest.ProtoReflect.Descriptor instead.
func (*InsertPointRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{7}
}

func (x *InsertPointRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *InsertPointRequest) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type ResponseInsertPoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Status         bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseInsertPoint) Reset() {
	*x = ResponseInsertPoint{}
	mi := &file_rag_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseInsertPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInsertPoint) ProtoMessage() {}

func (x *ResponseInsertPoint) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInsertPoint.ProtoReflect.Descriptor instead.
func (*ResponseInsertPoint) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseInsertPoint) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *ResponseInsertPoint) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// MatchOperator maps to ports.MatchOperator: "eq" or "in".
// For operator "eq":  set string_value / bool_value / int_value.
// For operator "in":  set string_values / int_values.
type FieldCondition struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Key      string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operator string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // "eq" | "in"
	// Scalar value (used with operator "eq")
	//
	// Types that are valid to be assigned to ScalarValue:
	//
	//	*FieldCondition_StringValue
	//	*FieldCondition_BoolValue
	//	*FieldCondition_IntValue
	ScalarValue isFieldCondition_ScalarValue `protobuf_oneof:"scalar_value"`
	// List values (used with operator "in")
	StringValues  []string `protobuf:"bytes,6,rep,name=string_values,json=stringValues,proto3" json:"string_values,omitempty"`
	IntValues     []int64  `protobuf:"varint,7,rep,packed,name=int_values,json=intValues,proto3" json:"int_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldCondition) Reset() {
	*x = FieldCondition{}
	mi := &file_rag_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldCondition) ProtoMessage() {}

func (x *FieldCondition) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldCondition.ProtoReflect.Descriptor instead.
func (*FieldCondition) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{9}
}

func (x *FieldCondition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *FieldCondition) GetScalarValue() isFieldCondition_ScalarValue {
	if x != nil {
		return x.ScalarValue
	}
	return nil
}

func (x *FieldCondition) GetStringValue() string {
	if x != nil {
		if x, ok := x.ScalarValue.(*FieldCondition_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FieldCondition) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.ScalarValue.(*FieldCondition_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FieldCondition) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.ScalarValue.(*FieldCondition_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FieldCondition) GetStringValues() []string {
	if x != nil {
		return x.StringValues
	}
	return nil
}

func (x *FieldCondition) GetIntValues() []int64 {
	if x != nil {
		return x.IntValues
	}
	return nil
}

type isFieldCondition_ScalarValue interface {
	isFieldCondition_ScalarValue()
}

type FieldCondition_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FieldCondition_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type FieldCondition_IntValue struct {
	IntValue int64 `protobuf:"varint,5,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*FieldCondition_StringValue) isFieldCondition_ScalarValue() {}

func (*FieldCondition_BoolValue) isFieldCondition_ScalarValue() {}

func (*FieldCondition_IntValue) isFieldCondition_ScalarValue() {}

// Filter maps to ports.Filter.
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Must          []*FieldCondition      `protobuf:"bytes,1,rep,name=must,proto3" json:"must,omitempty"`
	Should        []*FieldCondition      `protobuf:"bytes,2,rep,name=should,proto3" json:"should,omitempty"`
	MustNot       []*FieldCondition      `protobuf:"bytes,3,rep,name=must_not,json=mustNot,proto3" json:"must_not,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_rag_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{10}
}

func (x *Filter) GetMust() []*FieldCondition {
	if x != nil {
		return x.Must
	}
	return nil
}

func (x *Filter) GetShould() []*FieldCondition {
	if x != nil {
		return x.Should
	}
	return nil
}

func (x *Filter) GetMustNot() []*FieldCondition {
	if x != nil {
		return x.MustNot
	}
	return nil
}

// SearchPointRequest maps to ports.SearchQuery.
// vector_name: "text_dense" | "image_dense" | "bm25"
type SearchPointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	VectorName     string                 `protobuf:"bytes,2,opt,name=vector_name,json=vectorName,proto3" json:"vector_name,omitempty"`
	Vector         []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`               // dense vector; leave empty for BM25/lexical
	QueryText      string                 `protobuf:"bytes,4,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"` // text for BM25/lexical search
	Limit          uint64                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	ScoreThreshold *float32               `protobuf:"fixed32,6,opt,name=score_threshold,json=scoreThreshold,proto3,oneof" json:"score_threshold,omitempty"`
	WithPayload    bool                   `protobuf:"varint,7,opt,name=with_payload,json=withPayload,proto3" json:"with_payload,omitempty"`
	Filter         *Filter                `protobuf:"bytes,8,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchPointRequest) Reset() {
	*x = SearchPointRequest{}
	mi := &file_rag_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPointRequest) ProtoMessage() {}

func (x *SearchPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPointRequest.ProtoReflect.Descriptor instead.
func (*SearchPointRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchPointRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SearchPointRequest) GetVectorName() string {
	if x != nil {
		return x.VectorName
	}
	return ""
}

func (x *SearchPointRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchPointRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *SearchPointRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchPointRequest) GetScoreThreshold() float32 {
	if x != nil && x.ScoreThreshold != nil {
		return *x.ScoreThreshold
	}
	return 0
}

func (x *SearchPointRequest) GetWithPayload() bool {
	if x != nil {
		return x.WithPayload
	}
	return false
}

func (x *SearchPointRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// SearchResultItem is a single scored point returned from search.
type SearchResultItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultItem) Reset() {
	*x = SearchResultItem{}
	mi := &file_rag_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultItem) ProtoMessage() {}

func (x *SearchResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultItem.ProtoReflect.Descriptor instead.
func (*SearchResultItem) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResultItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResultItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResultItem) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResponseSearchPoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Results        []*SearchResultItem    `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseSearchPoint) Reset() {
	*x = ResponseSearchPoint{}
	mi := &file_rag_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseSearchPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSearchPoint) ProtoMessage() {}

func (x *ResponseSearchPoint) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSearchPoint.ProtoReflect.Descriptor instead.
func (*ResponseSearchPoint) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseSearchPoint) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *ResponseSearchPoint) GetResults() []*SearchResultItem {
	if x != nil {
		return x.Results
	}
	return nil
}

// DeletePointFilterRequest maps to (collectionName + ports.Filter).
type DeletePointFilterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Filter         *Filter                `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeletePointFilterRequest) Reset() {
	*x = DeletePointFilterRequest{}
	mi := &file_rag_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePointFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePointFilterRequest) ProtoMessage() {}

func (x *DeletePointFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePointFilterRequest.ProtoReflect.Descriptor instead.
func (*DeletePointFilterRequest) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePointFilterRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *DeletePointFilterRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ResponseDeletePointFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Status         bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResponseDeletePointFilter) Reset() {
	*x = ResponseDeletePointFilter{}
	mi := &file_rag_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDeletePointFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDeletePointFilter) ProtoMessage() {}

func (x *ResponseDeletePointFilter) ProtoReflect() protoreflect.Message {
	mi := &file_rag_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDeletePointFilter.ProtoReflect.Descriptor instead.
func (*ResponseDeletePointFilter) Descriptor() ([]byte, []int) {
	return file_rag_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResponseDeletePointFilter) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *ResponseDeletePointFilter) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_rag_service_proto protoreflect.FileDescriptor

const file_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x11rag_service.proto\"\\\n" +
	"\x16CollectionVectorConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\tR\bdistance\"\xf5\x01\n" +
	"\x10SchemaCollection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\avectors\x18\x02 \x03(\v2\x17.CollectionVectorConfigR\avectors\x12\x16\n" +
	"\x06shards\x18\x03 \x01(\rR\x06shards\x12-\n" +
	"\x12replication_factor\x18\x04 \x01(\rR\x11replicationFactor\x12&\n" +
	"\x0fon_disk_payload\x18\x05 \x01(\bR\ronDiskPayload\x12+\n" +
	"\x11optimizers_memmap\x18\x06 \x01(\bR\x10optimizersMemmap\"F\n" +
	"\x18ResponseCreateCollection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"-\n" +
	"\x17DeleteCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x18ResponseDeleteCollection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\":\n" +
	"\fVectorObject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\"\xa5\x01\n" +
	"\x05Point\x121\n" +
	"\fvectorObject\x18\x01 \x03(\v2\r.VectorObjectR\fvectorObject\x12-\n" +
	"\apayload\x18\x02 \x03(\v2\x13.Point.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x12InsertPointRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x1e\n" +
	"\x06points\x18\x02 \x03(\v2\x06.PointR\x06points\"V\n" +
	"\x13ResponseInsertPoint\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"\xf7\x01\n" +
	"\x0eFieldCondition\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x05 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\rstring_values\x18\x06 \x03(\tR\fstringValues\x12\x1d\n" +
	"\n" +
	"int_values\x18\a \x03(\x03R\tintValuesB\x0e\n" +
	"\fscalar_value\"\x82\x01\n" +
	"\x06Filter\x12#\n" +
	"\x04must\x18\x01 \x03(\v2\x0f.FieldConditionR\x04must\x12'\n" +
	"\x06should\x18\x02 \x03(\v2\x0f.FieldConditionR\x06should\x12*\n" +
	"\bmust_not\x18\x03 \x03(\v2\x0f.FieldConditionR\amustNot\"\xc1\x02\n" +
	"\x12SearchPointRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x1f\n" +
	"\vvector_name\x18\x02 \x01(\tR\n" +
	"vectorName\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12\x1d\n" +
	"\n" +
	"query_text\x18\x04 \x01(\tR\tqueryText\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x04R\x05limit\x12,\n" +
	"\x0fscore_threshold\x18\x06 \x01(\x02H\x00R\x0escoreThreshold\x88\x01\x01\x12!\n" +
	"\fwith_payload\x18\a \x01(\bR\vwithPayload\x12$\n" +
	"\x06filter\x18\b \x01(\v2\a.FilterH\x01R\x06filter\x88\x01\x01B\x12\n" +
	"\x10_score_thresholdB\t\n" +
	"\a_filter\"\xae\x01\n" +
	"\x10SearchResultItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x128\n" +
	"\apayload\x18\x03 \x03(\v2\x1e.SearchResultItem.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x13ResponseSearchPoint\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12+\n" +
	"\aresults\x18\x02 \x03(\v2\x11.SearchResultItemR\aresults\"d\n" +
	"\x18DeletePointFilterRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x1f\n" +
	"\x06filter\x18\x02 \x01(\v2\a.FilterR\x06filter\"\\\n" +
	"\x19ResponseDeletePointFilter\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status2\xd7\x02\n" +
	"\n" +
	"RagService\x12@\n" +
	"\x10CreateCollection\x12\x11.SchemaCollection\x1a\x19.ResponseCreateCollection\x12G\n" +
	"\x10DeleteCollection\x12\x18.DeleteCollectionRequest\x1a\x19.ResponseDeleteCollection\x128\n" +
	"\vInsertPoint\x12\x13.InsertPointRequest\x1a\x14.ResponseInsertPoint\x128\n" +
	"\vSearchPoint\x12\x13.SearchPointRequest\x1a\x14.ResponseSearchPoint\x12J\n" +
	"\x11DeletePointFilter\x12\x19.DeletePointFilterRequest\x1a\x1a.ResponseDeletePointFilterB)Z'rag_imagetotext_texttoimage/proto;protob\x06proto3"

var (
	file_rag_service_proto_rawDescOnce sync.Once
	file_rag_service_proto_rawDescData []byte
)

func file_rag_service_proto_rawDescGZIP() []byte {
	file_rag_service_proto_rawDescOnce.Do(func() {
		file_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)))
	})
	return file_rag_service_proto_rawDescData
}

var file_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_rag_service_proto_goTypes = []any{
	(*CollectionVectorConfig)(nil),    // 0: CollectionVectorConfig
	(*SchemaCollection)(nil),          // 1: SchemaCollection
	(*ResponseCreateCollection)(nil),  // 2: ResponseCreateCollection
	(*DeleteCollectionRequest)(nil),   // 3: DeleteCollectionRequest
	(*ResponseDeleteCollection)(nil),  // 4: ResponseDeleteCollection
	(*VectorObject)(nil),              // 5: VectorObject
	(*Point)(nil),                     // 6: Point
	(*InsertPointRequest)(nil),        // 7: InsertPointRequest
	(*ResponseInsertPoint)(nil),       // 8: ResponseInsertPoint
	(*FieldCondition)(nil),            // 9: FieldCondition
	(*Filter)(nil),                    // 10: Filter
	(*SearchPointRequest)(nil),        // 11: SearchPointRequest
	(*SearchResultItem)(nil),          // 12: SearchResultItem
	(*ResponseSearchPoint)(nil),       // 13: ResponseSearchPoint
	(*DeletePointFilterRequest)(nil),  // 14: DeletePointFilterRequest
	(*ResponseDeletePointFilter)(nil), // 15: ResponseDeletePointFilter
	nil,                               // 16: Point.PayloadEntry
	nil,                               // 17: SearchResultItem.PayloadEntry
}
var file_rag_service_proto_depIdxs = []int32{
	0,  // 0: SchemaCollection.vectors:type_name -> CollectionVectorConfig
	5,  // 1: Point.vectorObject:type_name -> VectorObject
	16, // 2: Point.payload:type_name -> Point.PayloadEntry
	6,  // 3: InsertPointRequest.points:type_name -> Point
	9,  // 4: Filter.must:type_name -> FieldCondition
	9,  // 5: Filter.should:type_name -> FieldCondition
	9,  // 6: Filter.must_not:type_name -> FieldCondition
	10, // 7: SearchPointRequest.filter:type_name -> Filter
	17, // 8: SearchResultItem.payload:type_name -> SearchResultItem.PayloadEntry
	12, // 9: ResponseSearchPoint.results:type_name -> SearchResultItem
	10, // 10: DeletePointFilterRequest.filter:type_name -> Filter
	1,  // 11: RagService.CreateCollection:input_type -> SchemaCollection
	3,  // 12: RagService.DeleteCollection:input_type -> DeleteCollectionRequest
	7,  // 13: RagService.InsertPoint:input_type -> InsertPointRequest
	11, // 14: RagService.SearchPoint:input_type -> SearchPointRequest
	14, // 15: RagService.DeletePointFilter:input_type -> DeletePointFilterRequest
	2,  // 16: RagService.CreateCollection:output_type -> ResponseCreateCollection
	4,  // 17: RagService.DeleteCollection:output_type -> ResponseDeleteCollection
	8,  // 18: RagService.InsertPoint:output_type -> ResponseInsertPoint
	13, // 19: RagService.SearchPoint:output_type -> ResponseSearchPoint
	15, // 20: RagService.DeletePointFilter:output_type -> ResponseDeletePointFilter
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rag_service_proto_init() }
func file_rag_service_proto_init() {
	if File_rag_service_proto != nil {
		return
	}
	file_rag_service_proto_msgTypes[9].OneofWrappers = []any{
		(*FieldCondition_StringValue)(nil),
		(*FieldCondition_BoolValue)(nil),
		(*FieldCondition_IntValue)(nil),
	}
	file_rag_service_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_service_proto_rawDesc), len(file_rag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_service_proto_goTypes,
		DependencyIndexes: file_rag_service_proto_depIdxs,
		MessageInfos:      file_rag_service_proto_msgTypes,
	}.Build()
	File_rag_service_proto = out.File
	file_rag_service_proto_goTypes = nil
	file_rag_service_proto_depIdxs = nil
}
